### add new book
POST http://localhost:8080/author/add
Content-Type: application/json

{
  "name":"Михаил Афанасьевич Булгаков"
}
###
POST http://localhost:8080/author/add
Content-Type: application/json

{
"name":"Оскар Уайльд"
}

###