### add new book
POST http://localhost:8080/book/add
Content-Type: application/json

{
  "title":"Мастер и Маргарита",
  "author":
  {
    "id":1,
    "name":"Михаил Афанасьевич Булгаков"
  }
}

### add new book wrong author
POST http://localhost:8080/book/add
Content-Type: application/json

{
  "title":"Три товарища",
  "author":
  {
    "id":2,
    "name":"Эрих Мария Ремарк"
  }
}

### get book
GET http://localhost:8080/book/Мастер и Маргарита

### get book not found
GET http://localhost:8080/book/Мастер и ...

### update book
POST http://localhost:8080/book/update
Content-Type: application/json

{
  "id":1,
  "title":"Театральный роман",
  "author":
  {
    "id":1,
    "name":"Михаил Афанасьевич Булгаков"
  }
}

### update book
POST http://localhost:8080/book/update
Content-Type: application/json

{
  "id":4,
  "title":"Театральный роман",
  "author":
  {
    "id":1,
    "name":"Михаил Афанасьевич Булгаков"
  }
}

### delete book
DELETE http://localhost:8080/book/remove
Content-Type: application/json

{
  "id":1,
  "title":"Театральный роман",
  "author":
  {
    "id":1,
    "name":"Михаил Афанасьевич Булгаков"
  }
}

### delete book
DELETE http://localhost:8080/book/remove
Content-Type: application/json

{
  "id":4,
  "title":"Театральный роман",
  "author":
  {
    "id":1,
    "name":"Михаил Афанасьевич Булгаков"
  }
}

###